name: Test Workflow

on: [push]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Hello message
        run: echo "✅ GitHub Actions is alive!"
