name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "✅ GitHub Actions is working!"
